name: Build Android App Bundle

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'android/**'
      - 'src/**'
      - 'public/**'
      - 'capacitor.config.json'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Sync Capacitor
      run: npx cap sync android
    
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    
    - name: Build Android App Bundle
      run: |
        cd android
        ./gradlew bundleRelease
    
    - name: Upload App Bundle
      uses: actions/upload-artifact@v3
      with:
        name: app-release-bundle
        path: android/app/build/outputs/bundle/release/app-release.aab
        retention-days: 7
    
    - name: Generate APK for testing
      run: |
        cd android
        ./gradlew assembleRelease
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 7