name: Build iOS App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ios/**'
      - 'src/**'
      - 'public/**'
      - 'capacitor.config.json'

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Sync Capacitor
      run: npx cap sync ios
    
    - name: Install CocoaPods dependencies
      run: |
        cd ios/App
        pod install
    
    - name: Build iOS App
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -sdk iphoneos \
          -derivedDataPath build \
          -archivePath build/App.xcarchive \
          archive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Create IPA (unsigned)
      run: |
        cd ios/App
        mkdir -p build/Payload
        cp -r build/App.xcarchive/Products/Applications/App.app build/Payload/
        cd build
        zip -r App-unsigned.ipa Payload
    
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: app-ios-unsigned
        path: ios/App/build/App-unsigned.ipa
        retention-days: 7